-- =============================================================================
-- Migration: RLS policies for project-documents storage bucket
-- Date:      2026-04-21
--
-- PURPOSE: The project-documents bucket is private (public = false). Access
--          is granted via signed URLs generated by the server, which requires
--          storage.objects RLS policies that allow project members to read
--          and write files in their project folder.
--
--          This migration creates those policies, mirroring the pattern used
--          for project-photos in 2026-04-09_private_photo_buckets.sql.
--
-- FOLDER CONVENTION: first path segment is project_id (UUID). Matches the
--                    path built in src/lib/actions/attachments.ts:
--                    `${projectId}/${entityType}/${entityId}/${ts}-${name}`
--
-- HOW TO APPLY:
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--   Idempotent — uses `drop policy if exists`, safe to re-run.
-- =============================================================================

-- SELECT: project members can read project documents
drop policy if exists "Project members can read project documents" on storage.objects;
create policy "Project members can read project documents"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'project-documents'
  and exists (
    select 1 from public.project_members
    where project_members.project_id = (storage.foldername(name))[1]::uuid
      and project_members.profile_id = auth.uid()
  )
);

-- INSERT: project members can upload project documents
drop policy if exists "Project members can upload project documents" on storage.objects;
create policy "Project members can upload project documents"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-documents'
  and exists (
    select 1 from public.project_members
    where project_members.project_id = (storage.foldername(name))[1]::uuid
      and project_members.profile_id = auth.uid()
  )
);

-- UPDATE: project members can update project documents
drop policy if exists "Project members can update project documents" on storage.objects;
create policy "Project members can update project documents"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'project-documents'
  and exists (
    select 1 from public.project_members
    where project_members.project_id = (storage.foldername(name))[1]::uuid
      and project_members.profile_id = auth.uid()
  )
)
with check (
  bucket_id = 'project-documents'
  and exists (
    select 1 from public.project_members
    where project_members.project_id = (storage.foldername(name))[1]::uuid
      and project_members.profile_id = auth.uid()
  )
);

-- DELETE: project members can delete project documents
drop policy if exists "Project members can delete project documents" on storage.objects;
create policy "Project members can delete project documents"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'project-documents'
  and exists (
    select 1 from public.project_members
    where project_members.project_id = (storage.foldername(name))[1]::uuid
      and project_members.profile_id = auth.uid()
  )
);

notify pgrst, 'reload schema';
